#!/usr/bin/env bash

HOST=''
IMAGE=''

VERSION=$(git branch --show-current | sed -E "s/release\/([0-9]?\.[0-9]?\.[0-9]?)/\1/")
BRANCH=$(git branch |grep "*" | awk '{print $2}')
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


git tag -a "v$VERSION" -m "version $VERSION"
git push --follow-tags --set-upstream origin "$BRANCH"

# Build the Docker image with latest code
docker build \
    -f ./Dockerfile \
    -t "$HOST/$IMAGE:$VERSION" \
    -t $HOST/$IMAGE:latest . || 1;

docker build \
    -f ./development/Dockerfile \
    -t "$HOST/$IMAGE-dev:$VERSION" || 1;

docker build \
    -f ./production/Dockerfile \
    -t "$HOST/$IMAGE-prod:$VERSION" \
    -t $HOST/$IMAGE:latest . || 1;

docker push "$HOST/$IMAGE:$VERSION"
docker push "$HOST/$IMAGE-dev:$VERSION"
docker push "$HOST/$IMAGE-prod:$VERSION"
docker push $HOST/$IMAGE:latest